import fs from "node:fs";
const p="scripts/check/purchase-invoice-price-difference-smoke.mjs";
let t=fs.readFileSync(p,"utf8");
const old="  await orderTable.locator('[data-act=\"open\"][data-target=\"purchase-receipt-line-picker\"]')";
const neu="  const orderHeaders = await orderTable.locator('thead th').evaluateAll((cells) => cells.map((cell) => cell.textContent.trim()));\n  expect(orderHeaders[6] === '验票数量' && orderHeaders[7] === '暂估单价' && orderHeaders[8] === '含税单价', width + ': 订单行暂估单价列位置错误，实际=' + orderHeaders.join('、'));\n  const orderEstimatedCells = await orderTable.locator('tbody tr[data-row-value] [data-column=\"estimatedUnitPrice\"]').evaluateAll((cells) => cells.map((cell) => cell.textContent.trim()));\n  expect(JSON.stringify(orderEstimatedCells.slice().sort()) === JSON.stringify(['15,200.00', '8,800.00']), width + ': 订单行暂估单价列未显示带出值，实际=' + JSON.stringify(orderEstimatedCells));\n  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n  await settlementTable.locator('[data-act=\"open\"][data-target=\"purchase-receipt-line-picker\"]')";
if(!t.includes(old)) throw new Error("anchor missing");
t=t.replace(old,neu);
t=t.replace("  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n","  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n");
fs.writeFileSync(t.includes("const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n  const settlementTable")?t.replace("  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n","  const settlementTable = detail.locator('#purchase-invoice-settlement-items');\n"):t,"utf8");
console.log("smoke updated");
