import fs from "node:fs";
const p="scripts/check/purchase-payment-pages-smoke.mjs";
let t=fs.readFileSync(p,"utf8");
const old="'序号', '采购类别', '采购名称', '规格', '单位', '验票数量', '含税单价'";
const neu="'序号', '采购类别', '采购名称', '规格', '单位', '验票数量', '暂估单价', '含税单价'";
const count=t.split(old).length-1;
console.log("occurrences:",count);
if(count<1) throw new Error("anchor missing");
t=t.split(old).join(neu);
fs.writeFileSync(p,t,"utf8");
console.log("updated");
