import fs from "node:fs";
const raw = fs.readFileSync("schemas/pages/procurement/purchase-invoice.json","utf8");
const L = raw.split(/\r?\n/);
const show=(key,before,after)=>{const i=L.findIndex(l=>l.includes(key));console.log("### "+key+" @line "+(i+1));for(let k=Math.max(0,i-before);k<Math.min(L.length,i+after);k++)console.log((k+1)+"|"+L[k].slice(0,240));};
show('"availableOrderLines"',1,6);
show('"rules"',1,4);
show('"overlays"',1,4);
show('"supplier-picker"',2,3);
console.log("### last overlay end / mockData start");
const m=L.findIndex(l=>l.includes('"mockData"'));
for(let k=m-6;k<m+6;k++)console.log((k+1)+"|"+L[k].slice(0,200));
console.log("total lines",L.length);
