import fs from "node:fs";
const t = fs.readFileSync("pages/procurement/purchase-invoice.html","utf8");
const i = t.indexOf('id="purchase-invoice-order-items"');
const seg = t.slice(i, t.indexOf("</table>", i));
const heads = [...seg.slice(0, seg.indexOf("</thead>")).matchAll(/<th[^>]*>([\s\S]*?)<\/th>/g)].map(m=>m[1].replace(/<[^>]+>/g,"").trim());
console.log("order table headers:", JSON.stringify(heads));
const bodyStart = seg.indexOf("<tbody>");
const firstRow = seg.slice(bodyStart, seg.indexOf("</tr>", bodyStart));
const cells = [...firstRow.matchAll(/<td[^>]*data-column="([^"]*)"[^>]*>([\s\S]*?)<\/td>/g)].map(m=>m[1]+"="+m[2].replace(/<[^>]+>/g,"").trim().slice(0,18));
console.log("first row cells:", JSON.stringify(cells));
console.log("has estimatedUnitPrice column:", heads.includes("暂估单价"), "| row has estimated field:", firstRow.includes('data-column="estimatedUnitPrice"'));
