const s = require('../schemas/pages/income/income-contract-schema.json');
const form = s.regions.find((r) => r.id === 'contract-form');
const basic = form.tabs.find((t) => t.key === 'basic');
const svc = basic.children.find((c) => c.id === 'service-table');
const plan = basic.children.find((c) => c.id === 'receipt-plan-table');
console.log('workflowActions:', JSON.stringify(s.workflowActions));
console.log('detailReviewEnabled:', JSON.stringify(s.detailReviewEnabled));
console.log('overlay ids:', JSON.stringify((s.overlays || []).map((o) => o.id)));
console.log('\nservice-table columns:', JSON.stringify((svc?.columns || []).map((c) => c.code)));
console.log('service-table footerSummary:', JSON.stringify(svc?.footerSummary));
console.log('service calculatedBy:', JSON.stringify((svc?.columns || []).filter((c) => c.calculatedBy).map((c) => c.code)));
console.log('\nplan selectable:', JSON.stringify(plan?.selectable));
console.log('plan actions:', JSON.stringify(plan?.actions));
console.log('plan columns:', JSON.stringify((plan?.columns || []).map((c) => c.code)));
console.log('plan receiptDate editableWhen:', JSON.stringify((plan?.columns || []).find((c) => c.code === 'receiptDate')?.editableWhen));