const fs = require('fs');
const raw = fs.readFileSync('schemas/pages/income/income-contract-schema.json', 'utf8');
console.log('file bytes:', raw.length, '| newlines:', (raw.match(/\n/g) || []).length);
const s = JSON.parse(raw);
console.log('policyProfile:', s.policyProfile);
console.log('createStatus:', JSON.stringify(s.createStatus));
console.log('detailEditableStatuses:', JSON.stringify(s.detailEditableStatuses));
console.log('detailSubmitEnabled:', JSON.stringify(s.detailSubmitEnabled));
console.log('pageActionCodes:', JSON.stringify(s.pageActions.map((a) => a.code)));
const create = s.pageActions.find((a) => a.code === 'create');
console.log('create action:', JSON.stringify(create));
console.log('has policyTrace:', Object.prototype.hasOwnProperty.call(s, 'policyTrace'));

console.log('\n--- rendered create button ---');
const html = fs.readFileSync('pages/income/income-contract-schema.html', 'utf8');
const btn = html.match(/<button[^>]*data-act="create"[^>]*>/g) || [];
btn.forEach((b) => console.log(' ', b));
const mtime = (p) => fs.statSync(p).mtime.toISOString();
console.log('\nschema mtime:', mtime('schemas/pages/income/income-contract-schema.json'));
console.log('html mtime  :', mtime('pages/income/income-contract-schema.html'));