const P=__dirname+'/../schemas/pages/fixed-asset/fixed-asset-return.json';
const s=require(P);
console.log('--- overlays[1],[2]:');
console.log(JSON.stringify(s.overlays.slice(1),null,1).slice(0,1800));
const rows=s.mockData&&s.mockData.rows?s.mockData.rows:s.mockData;
console.log('--- mockData type:', typeof rows, Array.isArray(rows)?rows.length:Object.keys(rows||{}));
if(Array.isArray(rows)) console.log('--- statuses:', rows.map(r=>r.status).join(','));
console.log('--- createStatus:', s.createStatus, '| primaryDeleteEnabledStatuses:', JSON.stringify(s.primaryDeleteEnabledStatuses));
console.log('--- approvalOverlay:', JSON.stringify(s.approvalOverlay));
console.log('--- workflowActions:', JSON.stringify(s.workflowActions));
console.log('--- rules:', JSON.stringify(s.rules).slice(0,800));
