import fs from "node:fs";
const s = JSON.parse(fs.readFileSync("schemas/pages/procurement/purchase-invoice.json","utf8"));
console.log("=== availableReceiptLines count", (s.mockData.availableReceiptLines||[]).length);
(s.mockData.availableReceiptLines||[]).slice(0,4).forEach(r=>console.log(JSON.stringify(r)));
console.log("=== orderItems count", (s.mockData.orderItems||[]).length);
(s.mockData.orderItems||[]).slice(0,3).forEach(r=>console.log(JSON.stringify(r)));
console.log("=== settlementItems count", (s.mockData.settlementItems||[]).length);
(s.mockData.settlementItems||[]).slice(0,3).forEach(r=>console.log(JSON.stringify(r)));
console.log("=== invoices with items ===");
(s.mockData.invoices||[]).forEach(v=>{ if((v.orderItems||[]).length||(v.settlementItems||[]).length) console.log(v.invoiceNo, v.status, "order", (v.orderItems||[]).length, "settle", (v.settlementItems||[]).length); });
