import fs from "node:fs";
const r = JSON.parse(fs.readFileSync("prototype-resources/components/component-registry.json","utf8"));
console.log("categories type:", Array.isArray(r.categories)?"array":"object", Object.keys(r.categories||{}).slice(0,20).join(","));
const names = new Set();
const collect=(o)=>{ if(Array.isArray(o)) return o.forEach(collect); if(o&&typeof o==="object"){ if(typeof o.name==="string") names.add(o.name); if(typeof o.component==="string") names.add(o.component); Object.values(o).forEach(collect);} };
collect(r.categories);
["Alert","Modal","EditableTable","ProTable","ProModalForm"].forEach(n=>console.log(n, names.has(n)?"registered":"MISSING"));
const raw = fs.readFileSync("schemas/pages/procurement/purchase-invoice.json","utf8");
console.log("indent2:", raw.startsWith('{\n  "'), "endsWithNewline:", raw.endsWith("\n"));
console.log("overlays ids:", (JSON.parse(raw).overlays||[]).map(o=>o.id).join(", "));
