import fs from "node:fs";
const p="schemas/pages/procurement/purchase-invoice.json";
const raw=fs.readFileSync(p,"utf8");
const eol=raw.includes("\r\n")?"\r\n":"\n";
const L=raw.split(/\r?\n/);
const i=L.findIndex(l=>l.trim()==='"ProDataSelectModal",');
if(i<0) throw new Error("anchor missing");
L.splice(i+1,0,'      "Modal",','      "Alert",');
fs.writeFileSync(p,L.join(eol),"utf8");
const s=JSON.parse(fs.readFileSync(p,"utf8"));
console.log("components:", s.resourceReference.components.join(", "));
