import fs from 'node:fs';
const file='scripts/check/cost-analysis-smoke.mjs';
let s=fs.readFileSync(file,'utf8');
const anchor="      const visibleRows = table.locator('tbody > tr:visible:not([data-filter-empty-row])');";
s=s.replace(anchor,anchor+`
      expect(await visibleRows.count() === 0, '初次进入不应展示列表数据');
      expect(await page.locator('[data-series-key]').count() === 0, '初次进入不应展示曲线');
      expect(await search.locator('[data-multi-option]:checked').count() === 2, '演示应预选两个对象');
      expect(await search.locator('[data-field="accountingPeriodRangeStart"]').inputValue() === '2026-01', '年度默认开始期间错误');
      expect(await search.locator('[data-field="accountingPeriodRangeEnd"]').inputValue() === '2026-12', '年度默认结束期间错误');
      await search.locator('[data-act="query"]').click();
      await page.waitForTimeout(100);
      expect((await table.locator('[data-record-count]').innerText()).trim() === '共 24 条记录', '年度查询应有两个对象各12个月');
      expect(await page.locator('[data-series-key]').count() === 2, '年度查询应有两条曲线');
      expect(await page.locator('[data-series-key]').first().locator('circle').count() === 12, '年度趋势应有12个月');
      const legendLayout = await page.locator('#' + testCase.code + '-cost-trend-chart').evaluate(root => {
        const plot = root.querySelector('.pro-chart-line-wrap').getBoundingClientRect();
        const legend = root.querySelector('.pro-chart-legend');
        return legend.getBoundingClientRect().left >= plot.right && getComputedStyle(legend).flexDirection === 'column';
      });
      expect(legendLayout, '图例未在图表右侧纵向排列');
      await page.screenshot({path:path.join(reportDir, testCase.code + '-cost-annual-' + width + '.png'),fullPage:true});
      await search.locator('[data-act="reset"]').click();
      await page.waitForTimeout(100);
      expect(await visibleRows.count() === 0 && await page.locator('[data-series-key]').count() === 0, '重置后应清空结果');
      await search.locator('[data-field="accountingPeriodRangeStart"]').fill('2026-09');
      await search.locator('[data-field="accountingPeriodRangeEnd"]').fill('2026-09');
      await search.locator('[data-act="query"]').click();
      await page.waitForTimeout(100);
`);
s=s.replaceAll('`${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, \'0\')}`',"'2026-09'");
s=s.replaceAll(".pro-chart-legend').count() === 0", ".pro-chart-legend').count() === 1");
s=s.replaceAll('重置后不应恢复图例','重置后图例应为空');
s=s.replace(".pro-chart-legend').count() === 1, '重置后图例应为空'", ".pro-chart-legend').count() === 0, '重置后图例应为空'");
s=s.replaceAll("=== '共 12 条记录', `${testCase.code}: 会计期间范围清空后未恢复全部列表`", "=== '共 0 条记录', `${testCase.code}: 无查询条件时不应加载列表`");
s=s.replace("=== '共 1 条记录', `${testCase.code}: 项目下拉筛选未生效`", "=== '共 12 条记录', `${testCase.code}: 项目下拉筛选未生效`");
s=s.replace("=== '共 2 条记录', '多项目列表筛选失败'", "=== '共 24 条记录', '多项目列表筛选失败'");
s=s.replaceAll("count() === 12, '重置未恢复全部", "count() === 0, '重置未清空");
s=s.replace("          expect(await page.locator('[data-series-key]').count() === 12, '未选部门时未展示全部曲线');", `          expect(await page.locator('[data-series-key]').count() === 0, '空条件不应展示曲线');
          await search.locator('[data-field="accountingPeriodRangeStart"]').fill('2026-01');
          await search.locator('[data-field="accountingPeriodRangeEnd"]').fill('2026-12');
          await search.locator('[data-act="query"]').click();
          await page.waitForTimeout(100);
          expect(await page.locator('[data-series-key]').count() === 12, '年度查询未恢复全部曲线');`);
s=s.replace("locator('circle').count() === 6", "locator('circle').count() === 12");
s=s.replace('trendAndSearchWidths.trend * 0.7','trendAndSearchWidths.trend * 0.6');
s=s.replace("        await table.locator(`tbody", `        await search.locator('[data-field="accountingPeriodRangeStart"]').fill('2026-09');
        await search.locator('[data-field="accountingPeriodRangeEnd"]').fill('2026-09');
        await search.locator('[data-act="query"]').click();
        await page.waitForTimeout(100);
        await table.locator(\`tbody`);
fs.writeFileSync(file,s);
